language: node_js
node_js:
  - lts/*

dist: trusty

addons:
  sonarcloud:
    organization: "jsulpis-github"
    token: $SONAR_TOKEN

cache: yarn

script:
  - yarn lint
  - yarn test:coverage
  - sonar-scanner
  - yarn generate

branches:
  only:
    - master
